# version: '3.8'

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     environment:
#       - DATABASE_URL=${DATABASE_URL}
#       - DIRECT_URL=${DIRECT_URL}
#       - SECRET_KEY=${SECRET_KEY}
#       - SMSIR_API_KEY=${SMSIR_API_KEY}
#       - MAIN_LINE_NUMBER=${MAIN_LINE_NUMBER}
#     ports:
#       - "3000:3000"
#     # Use .env file for environment variables
#     env_file:
#       - .env

version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped
